### ISSUE TITLE
Muted players (beerchat) using the tpr command

### ISSUE THREAD

**Issue by 6r1d** [ChaosWormz/teleport-request#13]
Hello, there is a [beerchat](https://github.com/pandorabox-io/beerchat) mod, which allows you to mute some players. But people don't stop on that and some muted players are constantly using their /tpr command for fun.

I was wondering if this mod can check if Beerchat exists on the server and the player making this teleport request is not muted?

**Comment by Panquesito7** [comment]
Yes, it should be possible, and easy. I'll create support with beerchat.
Note that I will add it in my [fork](https://github.com/Panquesito7/teleport-request) (and probably soon create a PR).
