### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by animetrom** [ChaosWormz/teleport-request#33]
Hello good afternoon!

I developed the "pt.po" file for your mod with the Brazilian Portuguese translation.

How can I get you to add it to the mod repository?

**Comment by Panquesito7** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by animetrom** [comment]
I just did it!

**Comment by Panquesito7** [comment]
You need to create a pull request in order to merge your changes into the original repository.

**Comment by Panquesito7** [comment]
Why are there 4 more lines than the template file?
Have you added translations from #30?
