### ISSUE TITLE
rename the mod

### ISSUE THREAD

**Issue by olliy1or** [ChaosWormz/teleport-request#41]
Minetest doesn't support mods with "-" in its name so i recommend changing the name of the mod to "teleport_request" instead of "teleport-request" 
![error](https://user-images.githubusercontent.com/55839810/109409551-8574d500-79b5-11eb-8583-956ff6166120.png)

**Comment by Panquesito7** [comment]
Are you sure you have `mod.conf` **exactly** as it is in the `master` branch?
`mod.conf` sets the name automatically to `tpr`; so if you change the folder name it should still work.

**Comment by ChaosWormz** [comment]
Changing the name here on the repo would break links, and make unnecessary difficulty  to those who would have update the mod git configuration to direct to the change link. this issue can be solved via: git clone https://github.com/ChaosWormz/teleport-request/ tpr

**Comment by Panquesito7** [comment]
`mod.conf` should already solve this issue. Closing.
